version: '3.7'
services:
  user-api:
    image: filipecsoares/user-api
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:h2:mem:users
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=password
  product-api:
    image: filipecsoares/product-api
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:h2:mem:products
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=password
  shopping-api:
    image: filipecsoares/shopping-api
    ports:
      - 8082:8082
    environment:
      - DATABASE_URL=jdbc:h2:mem:shopping
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=password
      - PRODUCT_API_URL=http://product:8081
      - USER_API_URL=http://user:8080