server:
  port: 8081
spring:
  application:
    name: product-api
  flyway:
    schemas: products
  datasource:
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 10000
    url: jdbc:h2:file:./data/product-api
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: products
